var myGolfLang = {
	"en": {
		"Feedback": {
			"title": "myGolf: Feedback",
			"OK": "OK",
			"CategoriesListError": "Categories Error",
			"FeedbackSuccessTitle": "Feedback",
			"FeedbackErrorTitle": "Error sending feedback",
			"FeedbackSuccessMessage": "Your feedback was sent successfully"
		},
		"ScoringPage": {
			"title": "myGolf2u - Scoring",
			"editTitle": "Editing Scorecard",
			"ScorePar": "Par",
			"GPS": "GPS",
			"GotoHole": "Go to",
			"HoleInOne": "Hole in One",
			"Albatross": "Albatross",
			"Eagle": "Eagle",
			"Birdie": "Birdie",
			"Par": "Par",
			"Bogey": "Bogey",
			"DoubleBogey": "Double Bogey",
			"TrippleBogey": "Triple Bogey",
			"Disaster": "Disaster",
			"GameCancelTitle": "Cancel Current Game",
			"GameCancelMessage": "This will delete the current game along with its scores. Do you want to continue?",
			"GameCancelYes": "Yes",
			"GameCancelNo": "No",
			"GameFinishTitle": "Finish Current Game",
			"GameFinishMessage": "Do you want to Save and Finish the current game?",
			"GameFinishYes": "Finish",
			"GameFinishNo": "No",
			"ReloadScoreTitle": "Reload Scorecard",
			"ReloadScoreMessage": "You have some unsaved scores. How would you like to proceed?",
			"MissingScoresTitle": "Missing Scores",
			"MissingScoresMessage": "Scores for all holes not filled in. Do you still want to finish the game?",
			"MissingScoresYes": "Finish",
			"MissingScoresNo": "No",
			"ScorerIs": "Scorer is"
		},
		"PlayerGroups": {
			"title": "Player Groups",
			"SelectAndReturn": "Select And Return",
			"SelectInstruction": "Click group name to select the player group"
		},
		"PlayerHomePage": {
			"title": "myGolf2u",
			"noauthtitle": "No Authentication",
			"noauthmessage": "You are not authenticated yet to get player stats",
			"newround": "New Round",
			"scorecards": "Scorecards",
			"competitions": "Competitions",
			"friends": "Friends",
			"NormalGameScoring": "Game in progress. Click to edit",
			"CompetitionScoring": "Go to scoring",
			"clickHereScoring": "Click here for scoring",
			"isInProgress": "is in progress",
			"Performance": "Performance",
			"playerJoined": "Joined",
			"playerIndex": "Index",
			"playerHandicap": "Handicap"
		},
		"CompetitionListPage": {
			"title": "myGolf: Competitions",
			"alert-title": "Competition List Error",
			"competitions": "Competitions",
			"displaying": "Displaying",
			"get-more": "Get More",
			"registered": "Registered",
			"slotsLeft": "slots",
			"playerParticipated": "played",
			"playerParticipating": "playing"
		},
		"ScorecardDisplay": {
			"Title": "Scorecard",
			"ReloadScorecard": "Reload Scorecard",
			"ReloadTitle": "Reload Scorecard",
			"ReloadMessage": "This will reload the scorecard from server. Do you want to continue?"
		},
		"SelectClub": {
			"title": "Select Club",
			"RecentClubs": "Recently Played",
			"NearBy": "Clubs Nearby",
			"displaying": "Displaying",
			"get-more": "Get More"
		},
		"SignIn": {
			"username": "Email",
			"password": "Password",
			"login": "Login",
			"mygolf-title": "MyGolf",
			"forgotpassword": "Forgot Password?",
			"signup": "Join Now"
		},
		"SignUpPage": {
			"email": "Email",
			"firstname": "First Name",
			"lastname": "Last Name",
			"password": "Password",
			"gender": "Gender",
			"male": "Male",
			"female": "Female",
			"handicap": "Handicap",
			"authentication": "Authentication",
			"re-enter-password": "Re-type password",
			"firstname-required": "* First name is required!",
			"firstname-maxlength": "* Maximum length of first name is 50!",
			"lastname-maxlength": "* Maximum length of last name is 50!",
			"handicap-required": "* Handicap must be required",
			"password-required": "* Password is required!",
			"password-minlength": "* Minimum length of the password is 6!",
			"password-maxlength": "* Maximum length of the password is 10!",
			"email-required": "* Email is mandatory!",
			"email-invalid": "* Invalid email entered!",
			"password-mismatch-title": "Password Mismatch",
			"password-mismatch-message": "Two passwords do no match",
			"alert-ok": "OK",
			"signup-error-title": "Sign up failure"
		},
		"ClubHomePage": {
			"title": "myGolf"
		},
		"CompetitionFlights": {
			"title": "Flights",
			"flightno": "Flight",
			"starttime": "T-Off",
			"starthole": "Hole",
			"playername": "Player",
			"handicap": "Handicap",
			"buggyno": "Buggy"
		},
		"CompetitionDetails": {
			"title": "Competition Details",
			"sponsor": "Sponsors",
			"players": "Players",
			"flights": "Flights",
			"prizes": "Prizes",
			"scorecard": "View Scorecard",
			"leaderboard": "Leaderboard",
			"clickdetails": "More details",
			"teams": "Teams",
			"teamLeaderboard": "Team Leaderboard"
		},
		"LeaderboardPage": {
			"title": "Leaderboard",
			"overall": "Overall",
			"positionL": "Position",
			"positionP": "Pos",
			"handicapL": "Handicap",
			"handicapP": "Hcp",
			"players": "Player",
			"toPar": "+/-",
			"grossL": "Gross",
			"grossP": "GRS",
			"netL": "Net",
			"netP": "NET",
			"onHole": "On"
		},
		"CompetitionFilter": {
			"title": "Competition Filter",
			"apply-filter": "Apply",
			"search-type-header": "By default, show me",
			"search-type-upcoming": "Upcoming",
			"search-type-all": "All",
			"search-type-private": "Private Only",
			"limit-header": "Limit result by:",
			"only-participating": "Competitions I've registered",
			"favorites-only": "My Favourite Clubs",
			"nearby-clubs": "Held in nearby clubs",
			"max-distance": "Max distance ",
			"membership-only": "Clubs I'm member of",
			"limit-by-dates": "Limit result by",
			"last-n-days": "Number of Days",
			"last-n-weeks": "Number Weeks",
			"last-n-months": "Number of Months",
			"last-n-years": "Number of Years",
			"custom-period": "Custom",
			"none": "None",
			"length": "No of ",
			"period": "Period Type",
			"startDate": "Start Date",
			"endDate": "End Date"
		},
		"CompetitionPlayersPage": {
			"title": "Players",
			"colPlayers": "Players",
			"colHandicap": "Hcp",
			"colMemberAccNo": "Mem #",
			"noDataFound": "No players found matching this filter."
		},
		"SponsorsPage1": {
			"title": "Sponsors",
			"colSponsor": "Sponsor",
			"colSponsorship": "Sponsorship"
		},
		"CompetitionTeams": {
			"title": "Teams",
			"flightno": "Flight",
			"starttime": "T-Off",
			"starthole": "Hole",
			"playername": "Player",
			"handicap": "Hcp",
			"buggyno": "Buggy",
			"team": "Team"
		},
		"PerformanceFilters": {
			"title": "Filters",
			"apply-filter": "Apply",
			"search-type-header": "By default, show me:",
			"search-type-upcoming": "Upcoming",
			"search-type-all": "All",
			"limit-header": "Limit result by:",
			"only-participating": "Competitions I've registered",
			"favorites-only": "My Favourite Clubs",
			"nearby-clubs": "Held in nearby clubs",
			"max-distance": "Max distance (KM)",
			"membership-only": "Clubs I'm member of",
			"limit-by-dates": "Limit result by :",
			"last-n-days": "Days",
			"last-n-weeks": "Weeks",
			"last-n-months": "Months",
			"last-n-years": "Years",
			"custom-period": "Custom",
			"none": "None",
			"length": "Length",
			"period": "Period",
			"startDate": "Start Date",
			"endDate": "End Date"
		},
		"PlayerChartsPage": {
			"title": "Performance",
			"info": "Info",
			"details": "Details",
			"statistics": "Statistics",
			"averageScore": "Average Score",
			"bestScore": "Best Score",
			"eagle": "Eagle",
			"birdie": "Birdie",
			"par": "Par",
			"bogey": "Bogey",
			"2bogey": "Double Bogey",
			"3bogey": "Triple Bogey or worse",
			"back": "Back"
		},
		"FlightSetup": {
			"title": "Flight Setup",
			"SelectPlayer": "Select Golfer"
		},
		"SelectCourses": {
			"title": "Select Courses",
			"NotSelected": "Not Playing Second Nine",
			"competitions": "competitions",
			"displaying": "Displaying",
			"get-more": "Get More"
		},
		"LeaderboardFiltersPage": {
			"title": "Filters",
			"apply": "Apply",
			"roundNoText": "Round No",
			"sortByText": "Sort By",
			"groupByText": "Group By",
			"gross": "Gross",
			"net": "Net",
			"noCategory": "No Category",
			"overall": "Overall"
		}
	},
	"hi": {
		"SignIn": {
			"mygolf": "गोल्फ",
			"golf": "गोल्फ",
			"username": "उपयोगकर्ता नाम",
			"password": "पासवर्ड",
			"signin": "लॉगिन",
			"remember-me": "मुझे याद रखना"
		}
	}
};